---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        grafana_actions: install,configure,state_control
        grafana_admin_password: testpassword
        grafana_state: started
